### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/sense-hat-puzzle-box#1]
Hi @LornaLynch @lauraclay could you take a look thanks.

**Comment by LornaLynch** [comment]
On it now :)

**Comment by LornaLynch** [comment]
In https://github.com/raspberrypilearning/sense-hat-puzzle-box/blob/master/comb_lock.md the images in the "Converting orientation to angles" section seem to be displaying oddly. They'll probably need to be checked in staging?

**Comment by jrobinson-uk** [comment]
https://staging.raspberrypi.org/learning/sense-hat-puzzle-box/comb_lock/

Looks okay here

**Comment by LornaLynch** [comment]
You're right: apologies!

**Comment by lauraclay** [comment]
I think we've done everything between us now :)
