### ISSUE TITLE
Puzzle box combination lock function

### ISSUE THREAD

**Issue by deunters** [raspberrypilearning/sense-hat-puzzle-box#10]
https://github.com/raspberrypilearning/sense-hat-puzzle-box/blob/master/comb_lock.md

To get it to work as shown on my pi, I had to change the x values to y and y to x:
 if y == -1:           # Checks the x and y values and decides on a corresponding angle
      angle= 180
  elif y == 1:           
      angle= 0
  elif x == -1:
      angle =  90
  else:
      angle = 270

**Comment by lawsie** [comment]
This resource has just been completely updated to our new format and will be going live very soon, so hopefully this issue will be resolved :)
