### ISSUE TITLE
Cover Art

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/sense-hat-puzzle-box#2]
@samalderhyde Some cover art would be great when you've got some time. The idea behind the resources is that they hide some secret information and several challenges or locks have to be broken before the message is revealed. The inspiration was a cryptex (da vinci code) type thing. Don't know if that helps.

There is also a component image that I need at some point for a GPS board, I'll leave it on my desk.
Thanks

**Comment by samalderhyde** [comment]
This sounds like fun. 
It's on the list.

I'll get the GPS board drawn up on Monday at the office.
